### ISSUE TITLE
Content element not working

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#37] opened 2018-09-20 05:13 UTC
When using a XAML like the following:

```xml
<Activity x:Class=""WFTemplate""
          xmlns=""http://schemas.microsoft.com/netfx/2009/xaml/activities""
          xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml"">
  <Sequence>
    <WriteLine>
      <Content>
        <Text>""HelloWorld""</Text>
      </Content>
    </WriteLine>
  </Sequence>
</Activity>
```

I get this exception:

```
Result Message:	Portable.Xaml.XamlObjectWriterException : The value  for 'Text' property is null
Result StackTrace:	
at Portable.Xaml.XamlObjectWriterInternal.OnWriteGetObject()
   at Portable.Xaml.XamlWriterInternalBase.WriteGetObject()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at CoreWf.XamlIntegration.FuncFactory`1.Evaluate() in C:\dev\corewf\src\CoreWf\XamlIntegration\FuncFactory.cs:line 91
   at CoreWf.DynamicActivity.OnInternalCacheMetadata(Boolean createEmptyBindings) in C:\dev\corewf\src\CoreWf\DynamicActivity.cs:line 122
   at CoreWf.Activity.InternalCacheMetadata(Boolean createEmptyBindings, IList`1& validationErrors) in C:\dev\corewf\src\CoreWf\Activity.cs:line 1074
   at CoreWf.ActivityUtilities.ProcessActivity(ChildActivity childActivity, ChildActivity& nextActivity, Stack`1& activitiesRemaining, ActivityCallStack parentChain, IList`1& validationErrors, ProcessActivityTreeOptions options, ProcessActivityCallback callback) in C:\dev\corewf\src\CoreWf\ActivityUtilities.cs:line 647
   at CoreWf.ActivityUtilities.ProcessActivityTreeCore(ChildActivity currentActivity, ActivityCallStack parentChain, ProcessActivityTreeOptions options, ProcessActivityCallback callback, IList`1& validationErrors) in C:\dev\corewf\src\CoreWf\ActivityUtilities.cs:line 910
   at CoreWf.ActivityUtilities.CacheRootMetadata(Activity activity, LocationReferenceEnvironment hostEnvironment, ProcessActivityTreeOptions options, ProcessActivityCallback callback, IList`1& validationErrors) in C:\dev\corewf\src\CoreWf\ActivityUtilities.cs:line 826
   at CoreWf.Hosting.WorkflowInstance.ValidateWorkflow(WorkflowInstanceExtensionManager extensionManager) in C:\dev\corewf\src\CoreWf\Hosting\WorkflowInstance.cs:line 376
   at CoreWf.Hosting.WorkflowInstance.RegisterExtensionManager(WorkflowInstanceExtensionManager extensionManager) in C:\dev\corewf\src\CoreWf\Hosting\WorkflowInstance.cs:line 182
   at CoreWf.WorkflowApplication.EnsureInitialized() in C:\dev\corewf\src\CoreWf\WorkflowApplication.cs:line 611
   at CoreWf.WorkflowApplication.RunInstance(WorkflowApplication instance) in C:\dev\corewf\src\CoreWf\WorkflowApplication.cs:line 1215
   at CoreWf.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout) in C:\dev\corewf\src\CoreWf\WorkflowApplication.cs:line 1245
   at CoreWf.WorkflowInvoker.Invoke(Activity workflow, TimeSpan timeout, WorkflowInstanceExtensionManager extensions) in C:\dev\corewf\src\CoreWf\WorkflowInvoker.cs:line 298
   at CoreWf.WorkflowInvoker.Invoke(Activity workflow, TimeSpan timeout) in C:\dev\corewf\src\CoreWf\WorkflowInvoker.cs:line 87
   at CoreWf.WorkflowInvoker.Invoke(Activity workflow) in C:\dev\corewf\src\CoreWf\WorkflowInvoker.cs:line 81
   at XamlTestCases.XamlTests.XamlWorkflowNoInputs(String xamlString) in C:\dev\corewf\src\XamlTestCases\XamlTests.cs:line 92
```

The `Content` element must not be setting the value of the `Text` property on `WriteLine`. Need to investigate why not.

**Comment by ewinnington** [comment] 2018-12-04 18:49
Hopefully with System.Xaml open now, we can solve such issues.

**Comment by bcisnero** [comment] 2019-06-12 23:05
Sorry again but what the help wanted label means in this context?

**Comment by lbargaoanu** [comment] 2019-06-13 03:23
Ideally a PR  with a fix.

**Comment by bcisnero** [comment] 2019-06-13 17:32
Ok, got it. Thanks!

**Comment by bcisnero** [comment] 2019-06-13 20:29
So can somebody please assign this to me? because I already started to investigate and although I haven't been able to reproduce the exception I'm going to keep trying to see if I can make it fail and also I'm going to do a little cleanup code by removing all or some of the compiler warnings and apply the VS 2019 code suggestions.

**Comment by lbargaoanu** [comment] 2019-06-14 03:39
Cleanup where? :) Because we kind of don't need right now a lot of insignificant changes across a code base we don't quite understand and with probably pretty low test coverage. It's just risky. If you're confident you can open a PR with a passing test similar to the XAML above, then we can close this issue. That's a useful contribution, and you can move on to smth else.

**Comment by bcisnero** [comment] 2019-06-14 11:06
Understood, I’ll try all the tests and if nothing fails then I submit the
PR, is that ok?

**Comment by lbargaoanu** [comment] 2019-06-14 11:08
Sure.

**Comment by ewinnington** [comment] 2019-06-14 20:30
The XAML provided is invalid. It doesn't work on the .net Framework with System.Xaml either: 

Message is: 
```
 System.InvalidOperationException: CacheMetadata for activity 'WFTemplate' threw 'System.Xaml.XamlObjectWriterException: 
Cannot create unknown type '{http://schemas.microsoft.com/netfx/2009/xaml/activities}Content'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at System.Activities.XamlIntegration.FuncFactory`1.Evaluate()
```

I get the same message in when the test is used on .net core with Portable.Xaml.
`
Message: Portable.Xaml.XamlObjectWriterException : Cannot create unknown type '{http://schemas.microsoft.com/netfx/2009/xaml/activities}Content'.`

Since we have the same behavior on both .net core with Portable and .net framework with System.Xaml, I don't see this as an issue.

**Closed as completed by ewinnington** 2019-06-14 20:30 UTC
Labels: help wanted
